name: lakhimpur_kheri
description: Application to resolve problems of people of the city.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  scoped_model: ^1.0.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: any


  #  firebase_ml_vision: ^0.2.0+2
  webfeed: ^0.4.2
  image_downloader: ^0.20.0
  flutter_custom_tabs: ^0.6.0
  provider: ^4.0.5
  liquid_pull_to_refresh: ^1.1.1
  share: 0.6.4+3
  shared_preferences: ^0.5.7+3
  intl: ^0.16.0
  font_awesome_flutter: ^8.4.0
  firebase_auth: any
  google_sign_in: ^4.0.11
  flutter_svg: any   # for BMI calculator in gym tab
  path_provider: any
  image_picker_gallery_camera: ^0.1.6
  gallery_saver: ^2.0.1


  # Block Pattern........................................................................
  firebase_core: ^0.4.3+3
  bloc: "4.0.0"
  flutter_bloc: "4.0.0"
  equatable: ^1.0.0
  meta: ^1.1.6

  # NewsBuzz-------------------------------------------------------------------------
  firebase_analytics: ^5.0.11
  firebase_database: ^3.1.3
  timeago: ^2.0.26
  flutter_swiper: ^1.1.4
  cached_network_image: ^2.0.0
  charts_flutter: any
  url_launcher: ^5.4.10
  flutter_localizations: # add this
    sdk: flutter # add this
  flutter_cupertino_localizations: ^1.0.1
  cloud_firestore: ^0.13.5
  image_picker: ^0.6.0+17
  firebase_storage: 3.1.6
  contact_picker: ^0.0.2
  photo_view: ^0.9.2
  english_words: ^3.1.5
  flutter_lorem: ^1.1.0
  rxdart: ^00.24.0
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.3
  http: ^0.12.0+4
  webview_flutter: ^0.3.19+9
  ff_navigation_bar: ^0.1.5
#  country_pickers:
#  country_code_picker:
#  flutter_country_picker:
  dynamic_theme: ^1.0.1
  flutter_material_color_picker: ^1.0.5
  flutter_picker: ^1.1.4
  firebase_ml_vision: ^0.9.3+8
  google_fonts: ^0.2.0
  flutter_icons: ^1.0.0+1
  fleva_icons: ^1.0.0
#  flutter_webview_plugin: any
#  firebase_mlkit_language: ^1.1.2

  geolocator: any
#  flutter_custom_clippers: ^0.1.1
  folding_cell: ^0.1.0

# Top ten news
  carousel_slider: ^1.3.1
  html_unescape: ^1.0.1+3
  flutter_webview_plugin: ^0.3.11
  pull_to_refresh: ^1.5.8
  transparent_image: ^0.1.0
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
#    - images/
    - assets/image/
    - assets/images/
    - assets/flags/
    - assets/smwallet/
    - assets/hotel/
#    - assets/icon/
    - assets/flare/
    - assets/fitness_app/
    - assets/fitness_app/wrestling.png
    - assets/quiz_images/
    - assets/locale/localization_en.json
    - assets/locale/localization_es.json
    - assets/quiz_json/cpp.json
    - assets/quiz_json/java.json
    - assets/quiz_json/js.json
    - assets/quiz_json/linux.json
    - assets/quiz_json/python.json
    - assets/efe-kurnaz.jpg
    - assets/rodion-kutsaev.jpeg
    - assets/steve-johnson.jpeg
    - assets/image/news.svg
    - assets/image/welcome.svg
    - assets/image/search.svg
    - assets/image/share.svg
    - assets/image/click-here.svg
    - assets/ae.png
    - assets/ar.png
    - assets/in.png
#    - assets/locale/localization_hi.json
      #    - lang/en.json
#    - lang/hn.json
#    - i18n/en.json
#    - i18n/ar.json




  #  - images/a_dot_burr.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quando
      fonts:
        - asset: fonts/Quando.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy.ttf
    - family: Alike
      fonts:
        - asset: fonts/Alike-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages




